#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

$commands = include "Commands/Registry.php";

// 第2引数は実行するコマンドです。
$inputCommand = $argv[1];

// PHPでインスタンス化できるコマンドのクラス名をすべて調べます。
foreach ($commands as $commandClass) {
    $alias = $commandClass::getAlias();

    if($inputCommand === $alias){
        if(in_array('--help',$argv)){
            fwrite(STDOUT, $commandClass::getHelp());
            exit(0);
        }
        else{
            $command = new $commandClass();
            $result = $command->execute();
            exit($result);
        }
    }
}

fwrite(STDOUT,"Failed to run any commands\n");